services:
  syntaxmono:
    image: syntaxmono
    build:
      context: apps/staff/node_modules/.vite/deps
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
